import { Geist, Geist_Mono, Russo_One } from "next/font/google";
import { russoOne } from "./fonts";
import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en' className='bodyBg'>
			<body className={`${russoOne.className} bodyBg`}>{children}</body>
		</html>
	);
}
